const data = {
    products: [
        {
            _id: '1',
            name: 'Whey Bulk Protein',
            category: 'Supplements',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Whey',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Whey Bulk Protein',
            category: 'Supplements',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Whey',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Whey Bulk Protein',
            category: 'Supplements',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Whey',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Whey Bulk Protein',
            category: 'Supplements',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Whey',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Whey Bulk Protein',
            category: 'Supplements',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Whey',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Whey Bulk Protein',
            category: 'Supplements',
            image: '/images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Whey',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ]
}

export default data;